library(shiny)
library(shinyFiles)
library(jsonlite)

datasetDescription_ui <- function(id) {
  ns <- NS(id)
  fluidPage(
  card(
    card_header("REQUIRED"),
    textInput(ns("Name"), label = "Dataset name: ", value = "")
  ),
  card(
    card_header("RECOMMENDED: General"),
    selectInput(ns("DatasetType"), label = "The interpretation of the dataset", choices = list("not specified" = "not specified", "raw" = "raw", "derivative" = "derivative"), selected = "not specified"),
    textInput(ns("License"), label = "The license for the dataset. Use of licence name abbreviations is RECOMMENDED.", value = "")
  ),
  card(
    card_header("RECOMMENDED: GeneratedBy"),
    textInput(ns("GeneratedBy_name"), label = "REQUIRED: Name", value = ""),
    textInput(ns("GeneratedBy_version"), label = "RECOMMENDED: Version", value = ""),
    textInput(ns("GeneratedBy_description"), label = "OPTIONAL: Description", value = ""),
    textInput(ns("GeneratedBy_CodeURL"), label = "OPTIONAL: CodeURL", value = ""),
    textInput(ns("GeneratedBy_ContainerTag"), label = "OPTIONAL: Container Tag", value = ""),
    textInput(ns("GeneratedBy_ContainerType"), label = "OPTIONAL: Container Type", value = ""),
    textInput(ns("GeneratedBy_ContainerURI"), label = "OPTIONAL: Container URI", value = ""),
    ),
  card(
    card_header("RECOMMENDED: SourceDatasets"),
    textInput(ns("SourceDatasets"), label = "SourceDatasets", value = "")
  ),
  card(
    card_header("OPTIONAL "),
    textInput(ns("Authors"), label = "List of authors involved in the project: ", value = ""),
    textInput(ns("Acknowledgements"), label = "Text acknowledging contributions of individuals or institutions beyond those listed in Authors or Funding", value = ""),
    textInput(ns("HowToAcknowledge"), label = "Instructions on how researchers using this dataset should acknowledge the original authors", value = ""),
    textInput(ns("Funding"), label = "List of sources of funding (grant numbers)", value = ""),
    textInput(ns("EthicsApprovals"), label = "List of ethics committee approvals of the research protocols and/or protocol identifiers.", value = ""),
    textInput(ns("ReferencesAndLinks"), label = "List of references to publication that contain information on the dataset, or links.", value = ""),
    textInput(ns("DatasetDOI"), label = "The Document Object Identifier of the dataset (not the corresponding paper).", value = "")
  ),
  card(
    actionButton(ns("save_json"), "Save JSON")
  )
  )
}

datasetDescription_server <- function(id, converted_root) {
  moduleServer(id, function(input, output, session) {
    observeEvent(input$save_json, {
      req(converted_root())
      # Main list containing the json Content
      dataset_description <- list()

      # Sub-lists for array entries
      generated_by <- list()

      # Sub-Sub lists
      container <- list()

      # Output path
      save_path <- file.path(converted_root(), "dataset_description.json")

      # Build the metadata list step by step
      # In order to make sure that no empty fields are included (cleaner)
      if (nzchar(input$Name)) dataset_description$Name <- input$Name
      dataset_description$BIDSVersion <- "1.4.0"  # always included

      # Dataset type, if specified
      if (input$DatasetType != "not specified") {
        dataset_description$DatasetType <- input$DatasetType
      }

      if (nzchar(input$License)) {
        dataset_description$License <- input$License
        }

      # Generated By
      if (nzchar(input$GeneratedBy_name)) {
        generated_by$Name <- input$GeneratedBy_name
      }

      if (nzchar(input$GeneratedBy_version)) {
        generated_by$Version <- input$GeneratedBy_Version
      }

      if (nzchar(input$GeneratedBy_description)) {
        generated_by$Description <- input$GeneratedBy_description
      }

      if (nzchar(input$GeneratedBy_CodeURL)) {
        generated_by$CodeURL <- input$GeneratedBy_CodeURL
      }

      # Container (inside Generated by)
      if (nzchar(input$GeneratedBy_ContainerTag)) {
        container$Tag <- input$GeneratedBy_ContainerTag
      }

      if (nzchar(input$GeneratedBy_ContainerType)) {
        container$Type <- input$GeneratedBy_ContainerType
      }

      if (nzchar(input$GeneratedBy_ContainerURI)) {
        container$URI <- input$GeneratedBy_ContainerURI
      }

      generated_by$Container <- container # Add to sub-list

      # Source Datasets
      if (nzchar(input$SourceDatasets)) {
        dataset_description$SourceDatasets <- input$SourceDatasets
        }

      # Authors
      authors <- strsplit(input$Authors, ",\\s*")[[1]]
      if (length(authors) > 0 && any(nzchar(authors))) {
        dataset_description$Authors <- authors
      }

      # Acknowledgements
      if (nzchar(input$Acknowledgements)) {
        dataset_description$Acknowledgements <- input$Acknowledgements
      }

      if (nzchar(input$HowToAcknowledge)) {
        dataset_description$HowToAcknowledge <- input$HowToAcknowledge
      }

      # Funding
      funding <- strsplit(input$Funding, ",\\s*")[[1]]
      if (length(funding) > 0 && any(nzchar(funding))) {
        dataset_description$Funding <- funding
      }

      # Ethics Approvals
      ethics <- strsplit(input$EthicsApprovals, "\n")[[1]]
      if (length(ethics) > 0 && any(nzchar(ethics))) {
        dataset_description$EthicsApprovals <- ethics
      }

      # References
      references <- strsplit(input$ReferencesAndLinks, "\n")[[1]]
      if (length(references) > 0 && any(nzchar(references))) {
        dataset_description$ReferencesAndLinks <- references
      }

      # Dataset DOI
      if (nzchar(input$DatasetDOI)) {
        dataset_description$DatasetDOI <- input$DatasetDOI
      }

      dataset_description$GeneratedBy <- list(generated_by)
      # Save as JSON file
      write_json(
        dataset_description,
        path = save_path,
        pretty = TRUE,
        auto_unbox = TRUE
      )

      showNotification("Saved as dataset_description.json", type = "message")
    })
  })
}
