library(stringr)
library(purrr)
# Description generated by ChatGPT
# =============================================================================
# Experimental Design Module for NIRS2BIDS
# =============================================================================
# This Shiny module allows the user to specify the study design for their
# fNIRS experiment.
#
# UI Function (experimentalDesign_ui):
#   - Lets the user define:
#       1) Total number of sessions in the experiment (numericInput)
#       2) Which sessions contain NIRS measurements (checkboxGroupInput)
#       3) Names of tasks for each NIRS session (dynamically generated textInput)
#   - Includes instructional text to guide the user
#   - Provides a "Confirm experimental design" button
#
# Server Function (experimentalDesign_server):
#   - Dynamically updates session and task inputs based on user selections
#   - Tracks which sessions have NIRS measurements
#   - Collects user-entered task names for NIRS sessions
#
# Inputs:
#   - input$total_sessions: number of sessions in the experiment
#   - input$nirs_sessions: vector of selected sessions containing NIRS ("Session 1", "Session 2" etc.)
#   - input$nirsTasks_<session_number>: user-defined task name for each NIRS session
#
# Outputs:
#   - Reactive list containing session structure:
#       all_folders: all session folder names (e.g., ses-01, ses-02, ...)
#       nirs_folders: folders for sessions with NIRS measurements
#   - writes a csv file (EXPNAME_tasks.csv) which
#   -> loads EXPNAME from the dataset description tab before
#   -> the file contains all NIRS tasks and corresponding sessions
#   -> multiple NIRS tasks can be separated by comma
# Notes:
#   - Input IDs for dynamic text fields are automatically generated
#     based on the selected NIRS sessions.
#   - Avoid spaces in input IDs to ensure reliable access via input[[...]].
# =============================================================================

#### EXPERIMENTAL DESIGN ####
experimentalDesign_ui <- function(id) {
  ns <- NS(id)
  fluidPage(
    # Specify experimental design
    card(
      style = "background-color: #f8f9fa;",
      div(
        style = "font-size: 1.05rem;",
        strong("Instruction:"),
        br(),
        "Please now specify the study design of your experiment.",
        br(),
        "A session is generally defined by a day on which data – whether fNIRS or not – has been recorded for a specific participant.",
        br(),
        "You are free, however, to declare two sessions which took place on the same day as separate, if that corresponds better to the specific study design (for example, if a recording takes place in the morning, the participant then sleeps and then another recording takes place in the afternoon)."
      )
    ),
    card(
      card_header("How many sessions take place in your experiment?"),
      numericInput(ns("total_sessions"), label = "Number of sessions: ", value = 1)
    ),
    # Specify sessions with NIRS measurements
    card(
      card_header("Which of this sessions contains a fNIRS measurement?"),
      checkboxGroupInput(
        ns("nirs_sessions"),
        label = "Please select the sessions containing a fNIRS measurement: ",
        choices = NULL,
        selected = NULL)),
    # Name the tasks for each of this sessions
    # The uiOutput is being generated dynamically depending on the selected NIRS sessions
    # (in output$nirs_task_inputs)
    card(
      card_header("You can now name the fNIRS tasks taking place in each session. These names will be part of the BIDS-compliant filenames. If multiple fNIRS tasks are part of one session, please separate the task names with a comma."),
      uiOutput(ns("nirs_task_inputs"))
    ),
    card(
      actionButton(ns("confirmExperimentalDesign"), "Confirm experimental design")
    )
  )
}

# Define server logic required to draw a histogram ----
experimentalDesign_server <- function(id, currentConvertedPathReactive, dataset_name_reactive) {
  moduleServer(id, function(input, output, session) {
    # Update number of choices for NIRS sessions
    # ... if the value of input$total_sessions changes
    observeEvent(input$total_sessions, {
      # Create names for each session
      nirs_sessions_choices <- paste0("Session ", seq_len(input$total_sessions))

      # Update the nirs_sessions input
      updateCheckboxGroupInput(session, "nirs_sessions",
                               choices = nirs_sessions_choices,
                               selected = nirs_sessions_choices)  # Optional: select first by default
    })

    # Create varying number of text inputs depending on the number of NIRS sessions
    # ! currently this creates a dynamic number of variables "nirsTasks_session"
    output$nirs_task_inputs <- renderUI({
      req(input$nirs_sessions)

      # Vector of strings of type "Session 1", "Session 4", etc.
      selected_sessions <- input$nirs_sessions

      # Adds new variables to the namespace of type "nirsTasks_<session_number>"
      # Each entry contains the tasks for a session

      lapply(selected_sessions, function(session_label) {
        textInput(
          inputId = session$ns(paste0("nirsTasks_", session_label)),  # Use full label
          label = paste(session_label, ":"),
          value = ""
        )
      })
    })

    # Define procedure for saving experiment description as csv
    # when clicking on "Confirm Experimental Design"
    observeEvent(input$confirmExperimentalDesign, {
      req(input$nirs_sessions)                     # at least one NIRS session
      req(input$total_sessions)                    # total sessions defined

      # Define path for saving data
      save_path <- file.path(here(), "R", "experiments", paste0(dataset_name_reactive(), "_tasks.csv"))
      if (!dir.exists(dirname(save_path))) {
        dir.create(dirname(save_path), recursive = TRUE)
      }

      # collect values of all variables named "nirsTasks_Session x"
      task_names <- map_chr(input$nirs_sessions, function(session_label) {
        input[[paste0("nirsTasks_", session_label)]]
      })

      names(task_names) <- input$nirs_sessions

      # Check for empty entries
      if (any(task_names == "" | is.na(task_names))) {
        showNotification(
          "One or more of the NIRS tasks is currently left empty. Please check you provided all names.",
          type = "error", duration = 5
        )
        return()  # stop further processing
      }

      # save CSV
      df <- tibble(session = names(task_names), task = task_names) %>%
        mutate(task = str_split(task, "\\s*,\\s*")) %>%
        unnest(task)
      write.csv(df, save_path, row.names = FALSE)
    })
  })
}
